name: csparse
version: 0.4.0
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: A concise sparse matrix package.
homepage: https://github.com/rwl/csparse
dev_dependencies:
  unittest: '>=0.11.0+3 <0.12.0'
